language: erlang
matrix:
    include:
      - otp_release: 21.3
      - otp_release: 20.3
      - otp_release: 19.3
      - otp_release: 18.3
        dist: trusty
      - otp_release: 17.4
        dist: trusty
sudo: false
script:
  - make test
  - make xref
notifications:
  email:
    recipients:
      - zotonic-commits@googlegroups.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
  irc:
    channels:
      - "chat.freenode.net#zotonic"
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
    template:
      - "New commit on %{repository_name}/%{branch} by %{author}:  %{message} (%{commit}) "
      - "Build details: %{build_url}"
